-- MySQL Script generated by MySQL Workbench
-- Tue Jul 25 13:48:11 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema yumdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `yumdb` ;

-- -----------------------------------------------------
-- Schema yumdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yumdb` DEFAULT CHARACTER SET utf8 ;
USE `yumdb` ;

-- -----------------------------------------------------
-- Table `yumdb`.`badge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yumdb`.`badge` ;

CREATE TABLE IF NOT EXISTS `yumdb`.`badge` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `name` CHAR(255) NULL DEFAULT NULL,
  `description` CHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `yumdb`.`session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yumdb`.`session` ;

CREATE TABLE IF NOT EXISTS `yumdb`.`session` (
  `ID` CHAR(255) NOT NULL,
  `password` CHAR(255) NULL DEFAULT NULL,
  `max` INT(11) NULL DEFAULT 5,
  `current` INT(11) NULL DEFAULT 0,
  `mode` CHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `yumdb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yumdb`.`user` ;

CREATE TABLE IF NOT EXISTS `yumdb`.`user` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `name` CHAR(255) NULL DEFAULT NULL,
  `email` CHAR(255) NULL DEFAULT NULL,
  `password` CHAR(255) NULL DEFAULT NULL,
  `nickname` CHAR(255) NULL DEFAULT NULL,
  `profile_img` CHAR(255) NULL DEFAULT NULL,
  `meal_remain` INT(11) NULL DEFAULT '3',
  `meal_last` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `yumdb`.`enterinfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yumdb`.`enterinfo` ;

CREATE TABLE IF NOT EXISTS `yumdb`.`enterinfo` (
  `session_ID` CHAR(255) NOT NULL,
  `user_ID` INT(11) NOT NULL,
  `role` CHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`session_ID`, `user_ID`),
  INDEX `FK_user_TO_enterInfo_1` (`user_ID` ASC),
  CONSTRAINT `FK_session_TO_enterInfo_1`
    FOREIGN KEY (`session_ID`)
    REFERENCES `yumdb`.`session` (`ID`),
  CONSTRAINT `FK_user_TO_enterInfo_1`
    FOREIGN KEY (`user_ID`)
    REFERENCES `yumdb`.`user` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `yumdb`.`friend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yumdb`.`friend` ;

CREATE TABLE IF NOT EXISTS `yumdb`.`friend` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `friend1_ID` INT(11) NULL DEFAULT NULL,
  `friend2_ID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_user_TO_friend_1`
    FOREIGN KEY (`ID`)
    REFERENCES `yumdb`.`user` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `yumdb`.`mybadge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yumdb`.`mybadge` ;

CREATE TABLE IF NOT EXISTS `yumdb`.`mybadge` (
  `user_Id` INT(11) NOT NULL,
  `badge_ID` INT(11) NOT NULL,
  PRIMARY KEY (`user_Id`, `badge_ID`),
  INDEX `FK_badge_TO_myBadge_1` (`badge_ID` ASC),
  CONSTRAINT `FK_badge_TO_myBadge_1`
    FOREIGN KEY (`badge_ID`)
    REFERENCES `yumdb`.`badge` (`ID`),
  CONSTRAINT `FK_user_TO_myBadge_1`
    FOREIGN KEY (`user_Id`)
    REFERENCES `yumdb`.`user` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `yumdb`.`trophy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yumdb`.`trophy` ;

CREATE TABLE IF NOT EXISTS `yumdb`.`trophy` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `name` CHAR(255) NULL DEFAULT NULL,
  `description` CHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `yumdb`.`mytrophy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yumdb`.`mytrophy` ;

CREATE TABLE IF NOT EXISTS `yumdb`.`mytrophy` (
  `user_ID` INT(11) NOT NULL,
  `trophy_ID` INT(11) NOT NULL,
  PRIMARY KEY (`user_ID`, `trophy_ID`),
  INDEX `FK_trophy_TO_myTrophy_1` (`trophy_ID` ASC),
  CONSTRAINT `FK_trophy_TO_myTrophy_1`
    FOREIGN KEY (`trophy_ID`)
    REFERENCES `yumdb`.`trophy` (`ID`),
  CONSTRAINT `FK_user_TO_myTrophy_1`
    FOREIGN KEY (`user_ID`)
    REFERENCES `yumdb`.`user` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `yumdb`.`yum`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yumdb`.`yum` ;

CREATE TABLE IF NOT EXISTS `yumdb`.`yum` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `name` CHAR(255) NULL DEFAULT NULL,
  `info` CHAR(255) NULL DEFAULT NULL,
  `img` CHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `yumdb`.`myyum`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yumdb`.`myyum` ;

CREATE TABLE IF NOT EXISTS `yumdb`.`myyum` (
  `user_ID` INT(11) NOT NULL,
  `yum_ID` INT(11) NOT NULL,
  PRIMARY KEY (`user_ID`, `yum_ID`),
  INDEX `FK_yum_TO_myYum_1` (`yum_ID` ASC),
  CONSTRAINT `FK_user_TO_myYum_1`
    FOREIGN KEY (`user_ID`)
    REFERENCES `yumdb`.`user` (`ID`),
  CONSTRAINT `FK_yum_TO_myYum_1`
    FOREIGN KEY (`yum_ID`)
    REFERENCES `yumdb`.`yum` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
