-- MySQL Script generated by MySQL Workbench
-- Mon Jul 17 12:17:35 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bobkemon
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bobkemon` ;

-- -----------------------------------------------------
-- Schema bobkemon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bobkemon` DEFAULT CHARACTER SET latin1 ;
USE `bobkemon` ;

-- -----------------------------------------------------
-- Table `bobkemon`.`pokemon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bobkemon`.`pokemon` ;

CREATE TABLE IF NOT EXISTS `bobkemon`.`pokemon` (
  `ID` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `info` VARCHAR(45) NULL DEFAULT NULL,
  `img` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bobkemon`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bobkemon`.`user` ;

CREATE TABLE IF NOT EXISTS `bobkemon`.`user` (
  `ID` INT(11) NOT NULL,
  `loginID` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `nickname` VARCHAR(45) NULL DEFAULT NULL,
  `profile_img` VARCHAR(45) NULL DEFAULT NULL,
  `meal_remain` VARCHAR(45) NULL DEFAULT NULL,
  `meal_last` DATE NULL DEFAULT NULL,
  `Pokemon_ID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Pokemon_ID_idx` (`Pokemon_ID` ASC) VISIBLE,
  CONSTRAINT `fk_User_Pokemon1`
    FOREIGN KEY (`Pokemon_ID`)
    REFERENCES `bobkemon`.`pokemon` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bobkemon`.`captured`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bobkemon`.`captured` ;

CREATE TABLE IF NOT EXISTS `bobkemon`.`captured` (
  `User_ID` INT(11) NOT NULL,
  `Pokemon_ID` INT(11) NOT NULL,
  PRIMARY KEY (`User_ID`, `Pokemon_ID`),
  INDEX `Pokemon_ID_idx` (`Pokemon_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Captured_Pokemon1`
    FOREIGN KEY (`Pokemon_ID`)
    REFERENCES `bobkemon`.`pokemon` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Captured_User`
    FOREIGN KEY (`User_ID`)
    REFERENCES `bobkemon`.`user` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bobkemon`.`friends`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bobkemon`.`friends` ;

CREATE TABLE IF NOT EXISTS `bobkemon`.`friends` (
  `User_ID` INT(11) NOT NULL,
  `Follower_ID` INT(11) NOT NULL,
  PRIMARY KEY (`User_ID`, `Follower_ID`),
  INDEX `Follower_ID_idx` (`Follower_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Friends_User1`
    FOREIGN KEY (`User_ID`)
    REFERENCES `bobkemon`.`user` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Friends_User2`
    FOREIGN KEY (`Follower_ID`)
    REFERENCES `bobkemon`.`user` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bobkemon`.`gallery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bobkemon`.`gallery` ;

CREATE TABLE IF NOT EXISTS `bobkemon`.`gallery` (
  `User_ID` INT(11) NOT NULL,
  `img` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`User_ID`),
  CONSTRAINT `fk_Gallery_User1`
    FOREIGN KEY (`User_ID`)
    REFERENCES `bobkemon`.`user` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
